name: crypt_io
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.3
  http: ^0.13.6
  get: ^4.6.5
  web3dart: ^2.6.1
  provider: ^6.0.1
  shared_preferences: ^2.1.1
  sliding_up_panel: ^2.0.0+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/